/**
 * Reading and writing the company's own record: `company_settings/main`.
 *
 * Two kinds of thing live in that document, and the distinction is why it exists at all.
 *
 * **Identity** (name, address, GSTIN, MSME, logo) used to be a hardcoded TypeScript constant, which
 * meant moving office required a developer and a deploy. It is company data, it changes, and the
 * people it changes for cannot edit code.
 *
 * **Marks** (the CEO's and CTO's signatures, the rubber stamp) belong to the business rather than
 * to whoever is signed in. An admin's personal signature already lives on their user record; these
 * are different. The offer letter a candidate receives should carry the CEO's signature whether it
 * was generated by the sales admin at 9am or the tech admin at midnight.
 *
 * This file is only the IO. The shapes and the merge rule are pure and live in `utils/company`, so
 * the policy that decides who signs what is testable without a database.
 */
import { doc, getDoc, onSnapshot, serverTimestamp, setDoc } from "firebase/firestore";
import { db } from "@/services/firebase";
import { EMPTY_COMPANY_ASSETS, type CompanyAssets } from "@/utils/company";

export {
  EMPTY_COMPANY_ASSETS,
  OFFICER_FALLBACK_TITLE,
  OFFICER_LABEL,
  officerCanSign,
  officerOf,
  resolveCompany,
} from "@/utils/company";
export type {
  CompanyAssets,
  CompanyOfficer,
  OfficerKey,
  ResolvedCompany,
} from "@/utils/company";

const COLLECTION = "company_settings";
const DOC_ID = "main";

export function watchCompanyAssets(cb: (assets: CompanyAssets) => void): () => void {
  return onSnapshot(
    doc(db, COLLECTION, DOC_ID),
    (snap) => cb(snap.exists() ? (snap.data() as CompanyAssets) : EMPTY_COMPANY_ASSETS),
    // A failed read must not blank an ID card that was rendering fine a moment ago.
    () => cb(EMPTY_COMPANY_ASSETS),
  );
}

export async function fetchCompanyAssets(): Promise<CompanyAssets> {
  try {
    const snap = await getDoc(doc(db, COLLECTION, DOC_ID));
    return snap.exists() ? (snap.data() as CompanyAssets) : EMPTY_COMPANY_ASSETS;
  } catch {
    return EMPTY_COMPANY_ASSETS;
  }
}

/** Merge, never overwrite: the stamp and the signature are set by different people, months apart. */
export async function saveCompanyAssets(patch: Partial<CompanyAssets>, byName: string): Promise<void> {
  await setDoc(
    doc(db, COLLECTION, DOC_ID),
    { ...patch, updatedAt: serverTimestamp(), updatedByName: byName },
    { merge: true },
  );
}
